### ISSUE TITLE
Reportando erro - 1a-Add

### ISSUE THREAD

**Issue by gabriellm1** [Insper/Z01#69]
Arquivo : I-VM\tests\tst\1a-Add

O teste do 1a-Add assume que o local esperado do temp 0 é o endereço 256 na ram quando na verdade o temp 0 se encontra no endereço 5 da RAM

como está:
    0 : 0000000100000001
  256 : 0000000010010010   
como deveria estar:
    0 : 0000000100000001
    5 : 0000000010010010

**Comment by rafaelcorsi** [comment]
corrigido
