### ISSUE TITLE
Reportando o erro no Main do mult - Projeto I

### ISSUE THREAD

**Issue by emanuellemoco** [Insper/Z01#70]
Arquivos: \I-VM\src\vmExamples\Mult\Main.vm

Ao usar o Windows, o teste do mult sempre sai como fail. Isso acontece, pois, a memória do Windows tem como padrão colocar undefined nas memórias que estão vazias. 
Solução: é necessário adicionar as duas últimas linhas abaixo no Main.vm:

function Main.main 0
	push constant 7
	push constant 2
	add
	push constant 3
	call mult 2
	label end
	goto end

**Comment by rafaelcorsi** [comment]
erro corrigido, já anotei seu ponto extra pela notificação do erro.
